Repository NCIOCPL/sitewide-search-app, pull requests merged in 2020-07, with the labels that each got.

#13 (#1) Search Results Page
  cypress/integration/AppAnalytics/BasicSearchResultsPageLoad.feature
  cypress/integration/AppAnalytics/NoResultsFoundPageLoad.feature
  cypress/integration/BasicResultsPageEnglish.feature
  cypress/integration/BasicResultsPageSpanish.feature
  cypress/integration/common/index.js
  src/__tests__/App.test.js
  src/components/molecules/no-results/no-results.jsx
  src/components/molecules/search-results-list/__tests__/result-list-item.test.js
  src/components/molecules/search-results-list/__tests__/search-results-list.test.js
  src/components/molecules/search-results-list/results-list-item.jsx
  src/components/molecules/search-results-list/search-results-list.jsx
  src/components/molecules/search-results-list/search-results-list.scss
  src/constants.js
  src/hooks/index.js
  src/hooks/samples/UseCustomQuery.jsx
  src/hooks/useURLQuery.js
  src/index.js
  src/services/api/actions/__tests__/getSearchResults.test.js
  src/services/api/actions/getSearchResults.js
  src/services/api/endpoints.js
  src/utils/i18n.js
  src/views/Home/Home.jsx
  src/views/Home/__tests__/Home.en.test.js
  support/mock-data/Search/cgov/en/all/achoo.json
  support/mock-data/Search/cgov/en/all/cancer.json
  support/mock-data/Search/cgov/en/all/tumor.json
  support/mock-data/Search/cgov/es/all/video.json
  support/mock-data/sitewidesearch/v1/search/english/cancer.json
  support/src/setupProxy.js
Labels: Passed UX Review

#15 (#5) Definition Display
  cypress/integration/BasicResultsPageSpanish.feature
  cypress/integration/DefinitionEnglish.feature
  cypress/integration/DefinitionSpanish.feature
  cypress/integration/common/beforeEach.js
  cypress/integration/common/index.js
  public/index.css
  public/index.html
  src/components/index.js
  src/components/molecules/definition/__tests__/definition.test.js
  src/components/molecules/definition/definition.jsx
  src/components/molecules/definition/definition.scss
  src/components/molecules/definition/index.js
  src/components/molecules/no-results/index.js
  src/components/molecules/pronunciation/pronunciation.jsx
  src/components/molecules/pronunciation/pronunciation.scss
  src/components/molecules/search-results-list/__tests__/search-results-list.test.js
  src/components/molecules/search-results-list/search-results-list.jsx
  src/hooks/__tests__/useURLQuery.test.js
  src/index.js
  src/services/api/actions/__tests__/getDictionaryResults.test.js
  src/services/api/actions/getDictionaryResults.js
  src/services/api/actions/index.js
  src/services/api/endpoints.js
  src/styles/sitewide-search.scss
  src/utils/i18n.js
  src/utils/index.js
  src/utils/strings.js
  src/views/Home/Home.jsx
  src/views/Home/Home.scss
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/en/caloric intake.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/en/cancer.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/en/metastasis.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/en/tumor.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/es/cáncer de la vagina en estadio lll.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/es/cáncer de mama.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/es/cáncer.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/es/metástasis.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/es/tumor.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/es/video.json
  support/src/setupProxy.js
Labels: Needs QA Review, Passed UX Review

#29 (#19) Use Pretty URL if it exists
  cypress/integration/DefinitionEnglish.feature
  cypress/integration/DefinitionSpanish.feature
  src/components/molecules/definition/definition.jsx
Labels: Passed QA Review, Ready to Merge

#27 (#25) Term name - no pronunciation
  src/components/molecules/definition/definition.jsx
  src/components/molecules/definition/definition.scss
  src/components/molecules/pronunciation/pronunciation.jsx
Labels: Passed QA Review, Ready to Merge, bug

#23 (#21) Search Terms Without Definition
  cypress/integration/DefinitionEnglish.feature
  cypress/integration/common/index.js
  src/components/molecules/definition/definition.jsx
  src/components/molecules/search-results-list/results-list-item.jsx
  support/mock-data/Search/cgov/en/all/dceg.json
Labels: Passed UX Review, Ready to Merge, bug

#24 (#20) Definition Box Padding
  src/components/molecules/definition/definition.scss
Labels: Passed UX Review, Ready to Merge

#28 (#26) Truncated Definition Sentence
  src/utils/strings.js
Labels: Passed UX Review, bug

#18 (#2) Result Pager
  cypress/integration/AppAnalytics/NoResultsFoundPageLoad.feature
  cypress/integration/ResultsPagerEnglish.feature
  cypress/integration/ResultsPagerSpanish.feature
  cypress/integration/common/index.js
  public/index.html
  src/App.js
  src/components/molecules/definition/definition.scss
  src/components/molecules/no-results/no-results.jsx
  src/components/molecules/search-results-list/__tests__/result-list-item.test.js
  src/components/molecules/search-results-list/__tests__/search-results-list.test.js
  src/components/molecules/search-results-list/search-results-list.jsx
  src/components/molecules/search-results-list/search-results-list.scss
  src/components/molecules/search-results-pager/__tests__/search-results-pager.test.js
  src/components/molecules/search-results-pager/search-results-pager.jsx
  src/components/molecules/search-results-pager/search-results-pager.scss
  src/constants.js
  src/hooks/routing.js
  src/services/api/actions/__tests__/getSearchResults.test.js
  src/services/api/actions/getSearchResults.js
  src/styles/breakpoints.scss
  src/utils/i18n.js
  src/views/Home/Home.jsx
  support/mock-data/Search/cgov/en/all/dceg_0-20.json
  support/mock-data/Search/cgov/en/all/dceg_1-20.json
  support/mock-data/Search/cgov/en/all/tumor_0-20.json
  support/mock-data/Search/cgov/en/all/tumor_1-20.json
  support/mock-data/Search/cgov/en/all/tumor_101-20.json
  support/mock-data/Search/cgov/en/all/tumor_21-20.json
  support/mock-data/Search/cgov/en/all/tumor_41-20.json
  support/mock-data/Search/cgov/en/all/tumor_61-20.json
  support/mock-data/Search/cgov/en/all/tumor_81-20.json
  support/mock-data/Search/cgov/es/all/tumor_0-20.json
  support/mock-data/Search/cgov/es/all/tumor_1-20.json
  support/mock-data/Search/cgov/es/all/tumor_101-20.json
  support/mock-data/Search/cgov/es/all/tumor_21-20.json
  support/mock-data/Search/cgov/es/all/tumor_41-20.json
  support/mock-data/Search/cgov/es/all/tumor_61-20.json
  support/mock-data/Search/cgov/es/all/tumor_81-20.json
  support/mock-data/Search/cgov/es/all/video_0-20.json
  support/mock-data/Search/cgov/es/all/video_1-20.json
  support/src/setupProxy.js
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#30 (#22) Add DCEG and Other Sites to React Dev for SWS
  cypress/integration/BasicResultsPageOtherSites/DCEGBasicResults.feature
  cypress/integration/BasicResultsPageOtherSites/NCIConnectBasicResultsEnglish.feature
  cypress/integration/BasicResultsPageOtherSites/NCIConnectBasicResultsSpanish.feature
  cypress/integration/DefinitionSpanish.feature
  cypress/integration/common/beforeEach.js
  cypress/integration/common/index.js
  public/index.html
  src/__tests__/App.test.js
  src/components/index.js
  src/components/molecules/definition/__tests__/definition.test.js
  src/components/molecules/definition/definition.jsx
  src/components/molecules/search-results-list/__tests__/search-results-list.test.js
  src/components/molecules/search-results-list/index.js
  src/components/molecules/search-results-list/search-results-list.jsx
  src/components/molecules/search-results-pager/__tests__/search-results-pager.test.js
  src/components/molecules/search-results-pager/search-results-pager.jsx
  src/hooks/__tests__/customFetch.test.js
  src/hooks/samples/UseCustomQuery.jsx
  src/index.js
  src/services/api/actions/__tests__/getDictionaryResults.test.js
  src/services/api/actions/__tests__/getSearchResults.test.js
  src/services/api/actions/getDictionaryResults.js
  src/services/api/actions/getSearchResults.js
  src/services/api/axios-client.js
  src/services/api/endpoints.js
  src/views/Home/Home.jsx
  src/views/Home/__tests__/Home.en.test.js
  support/mock-data/Search/doc/en/dceg.cancer.gov/cancer_0-20.json
  support/mock-data/Search/doc/en/www.cancer.gov/rare-brain-spine-tumor/tumor_0-20.json
  support/mock-data/Search/doc/es/www.cancer.gov/rare-brain-spine-tumor/tumor_0-20.json
  support/src/setupProxy.js
Labels: Passed QA Review, Passed UX Review

#32 (#4) Display Best Bets
  cypress/integration/BasicResultsPageOtherSites/DCEGBasicResults.feature
  cypress/integration/BasicResultsPageOtherSites/NCIConnectBasicResultsEnglish.feature
  cypress/integration/BestBetsEnglish.feature
  cypress/integration/BestBetsSpanish.feature
  cypress/integration/common/index.js
  public/index.html
  src/__tests__/App.test.js
  src/components/index.js
  src/components/molecules/best-bet/__tests__/best-bet.test.js
  src/components/molecules/best-bet/best-bet.jsx
  src/components/molecules/best-bet/best-bet.scss
  src/components/molecules/best-bet/index.js
  src/components/molecules/search-results-list/search-results-list.scss
  src/constants.js
  src/hooks/__tests__/customFetch.test.js
  src/index.js
  src/services/api/actions/getBestBetResults.js
  src/services/api/actions/index.js
  src/services/api/axios-client.js
  src/services/api/endpoints.js
  src/styles/sitewide-search.scss
  src/utils/i18n.js
  src/views/Home/Home.jsx
  support/mock-data/Search/cgov/en/all/cancer risk assessment tools_0-20.json
  support/mock-data/Search/cgov/en/all/ctep_0-20.json
  support/mock-data/Search/cgov/es/all/Medicamentos para el cancer_0-20.json
  support/mock-data/Search/doc/en/dceg.cancer.gov/cancer risk assessment tools_0-20.json
  support/mock-data/Search/doc/en/www.cancer.gov/rare-brain-spine-tumor/cancer risk assessment tools_0-20.json
  support/mock-data/bestbets/v1/BestBets/live/en/cancer risk assessment tools.json
  support/mock-data/bestbets/v1/BestBets/live/en/ctep.json
  support/mock-data/bestbets/v1/BestBets/live/es/Medicamentos para el cancer.json
  support/src/setupProxy.js
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#37 (#33) Mobie ViewBy Fix
  src/components/molecules/search-results-list/search-results-list.jsx
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#41 Bugfix: text wrapping issues on mobile
  src/components/molecules/pronunciation/pronunciation.scss
  src/components/molecules/search-results-list/search-results-list.scss
Labels: Passed QA Review, Passed UX Review, Ready to Merge
