Repository NCIOCPL/sitewide-search-app, pull requests merged in 2020-08, with the labels that each got.

#38 (#6) Display BestBets and Definition
  cypress/integration/BasicResultsPageOtherSites/DCEGBasicResults.feature
  cypress/integration/BestBetsAndDictionaryDisplay.feature
  src/components/molecules/definition/__tests__/definition.test.js
  src/components/molecules/definition/definition.scss
  src/views/Home/Home.jsx
  src/views/Home/Home.scss
  support/mock-data/Search/cgov/en/all/carcinoma_0-20.json
  support/mock-data/bestbets/v1/BestBets/live/en/carcinoma.json
  support/mock-data/bestbets/v1/BestBets/live/es/carcinoma.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/en/carcinoma.json
  support/mock-data/glossary/v1/Terms/search/Cancer.gov/Patient/es/carcinoma.json
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#52 (#48) BestBet Multiple Content Mismatch
  cypress/integration/BestBetsSpanish.feature
  src/components/molecules/best-bet/__tests__/best-bet.test.js
  src/components/molecules/best-bet/best-bet.jsx
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#31 (#14) Search type exact
  public/index.html
  src/services/api/actions/__tests__/getDictionaryResults.test.js
  src/services/api/actions/getDictionaryResults.js
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#50 (#46) Definition Link Click analytics
  cypress/integration/AppAnalytics/DefinitionLinkClick.feature
  cypress/integration/common/index.js
  src/components/molecules/definition/__tests__/definition.test.js
  src/components/molecules/definition/definition.jsx
Labels: Passed QA Review

#56 (#39) BestBets link click analytics
  cypress/integration/AppAnalytics/BestBetsLinkClick.feature
  cypress/integration/common/index.js
  package.json
  src/components/molecules/best-bet/__tests__/best-bet.test.js
  src/components/molecules/best-bet/best-bet.jsx
  src/utils/closest.js
  src/utils/index.js
  src/views/Home/__tests__/Home.en.test.js
  support/mock-data/bestbets/v1/BestBets/live/en/visual dcis.json
Labels: Needs QA Review, Needs Technical Review

#55 (#43) Analytics: Other Search Results Click
  cypress/integration/AppAnalytics/SearchResultsTitleClick.feature
  cypress/integration/common/index.js
  src/components/molecules/search-results-list/__tests__/result-list-item.test.js
  src/components/molecules/search-results-list/results-list-item.jsx
  src/components/molecules/search-results-list/search-results-list.jsx
Labels: Needs Technical Review, Passed QA Review

#47 (#44) Offset param in page query
  cypress/integration/AppAnalytics/BasicSearchResultsPageLoad.feature
  cypress/integration/AppAnalytics/SearchResultsTitleClick.feature
  cypress/integration/BasicResultsPageEnglish.feature
  cypress/integration/ResultsPagerEnglish.feature
  cypress/integration/ResultsPagerSpanish.feature
  cypress/integration/common/index.js
  src/components/molecules/search-results-list/__tests__/search-results-list.test.js
  src/components/molecules/search-results-list/search-results-list.jsx
  src/components/molecules/search-results-pager/__tests__/search-results-pager.test.js
  src/components/molecules/search-results-pager/search-results-pager.jsx
  src/services/api/actions/getSearchResults.js
  src/utils/__tests__/url.test.js
  src/views/Home/Home.jsx
  src/views/Home/__tests__/Home.en.test.js
  support/mock-data/Search/cgov/en/all/cancer risk assessment tools_20-20.json
  support/mock-data/Search/cgov/en/all/cancer risk assessment tools_40-20.json
  support/mock-data/Search/cgov/en/all/cancer_0-20.json
  support/mock-data/Search/cgov/en/all/cancer_20-20.json
  support/mock-data/Search/cgov/en/all/carcinoma_20-20.json
  support/mock-data/Search/cgov/en/all/carcinoma_40-20.json
  support/mock-data/Search/cgov/en/all/dceg.json
  support/mock-data/Search/cgov/en/all/dceg_1-20.json
  support/mock-data/Search/cgov/en/all/tumor.json
  support/mock-data/Search/cgov/en/all/tumor_0-20.json
  support/mock-data/Search/cgov/en/all/tumor_1-20.json
  support/mock-data/Search/cgov/en/all/tumor_100-20.json
  support/mock-data/Search/cgov/en/all/tumor_101-20.json
  support/mock-data/Search/cgov/en/all/tumor_160-20.json
  support/mock-data/Search/cgov/en/all/tumor_20-20.json
  support/mock-data/Search/cgov/en/all/tumor_21-20.json
  support/mock-data/Search/cgov/en/all/tumor_40-20.json
  support/mock-data/Search/cgov/en/all/tumor_41-20.json
  support/mock-data/Search/cgov/en/all/tumor_60-20.json
  support/mock-data/Search/cgov/en/all/tumor_61-20.json
  support/mock-data/Search/cgov/en/all/tumor_660-20.json
  support/mock-data/Search/cgov/en/all/tumor_80-20.json
  support/mock-data/Search/cgov/en/all/tumor_81-20.json
  support/mock-data/Search/cgov/es/all/carcinoma_0-20.json
  support/mock-data/Search/cgov/es/all/carcinoma_20-20.json
  support/mock-data/Search/cgov/es/all/carcinoma_40-20.json
  support/mock-data/Search/cgov/es/all/tumor_0-20.json
  support/mock-data/Search/cgov/es/all/tumor_1-20.json
  support/mock-data/Search/cgov/es/all/tumor_101-20.json
  support/mock-data/Search/cgov/es/all/tumor_20-20.json
  support/mock-data/Search/cgov/es/all/tumor_21-20.json
  support/mock-data/Search/cgov/es/all/tumor_40-20.json
  support/mock-data/Search/cgov/es/all/tumor_41-20.json
  support/mock-data/Search/cgov/es/all/tumor_60-20.json
  support/mock-data/Search/cgov/es/all/tumor_61-20.json
  support/mock-data/Search/cgov/es/all/tumor_80-20.json
  support/mock-data/Search/cgov/es/all/tumor_81-20.json
  support/mock-data/Search/cgov/es/all/video.json
  support/mock-data/Search/cgov/es/all/video_1-20.json
  support/src/setupProxy.js
Labels: Passed QA Review, Ready to Merge

#62 (#61) Analytics: Page Load Capture for Best Bet\Dictionary display
  cypress/integration/AppAnalytics/BasicSearchResultsPageLoad.feature
  cypress/integration/AppAnalytics/BestBetsLinkClick.feature
  cypress/integration/AppAnalytics/NoResultsFoundPageLoad.feature
  cypress/integration/BestBetsEnglish.feature
  cypress/integration/common/analytics.js
  src/views/Home/Home.jsx
  support/mock-data/Search/cgov/en/all/achoo.json
  support/mock-data/Search/cgov/en/all/cancer_0-20.json
  support/mock-data/Search/cgov/en/all/ctep_0-20.json
  support/mock-data/bestbets/v1/BestBets/live/en/tumor.json
Labels: Needs QA Review, Needs Technical Review

#59 (#57) IE Definition Box Wrap on Large Viewports
  src/views/Home/Home.scss
Labels: Needs Technical Review

#51 (#49) fix low level security vulnerabilities with npm audit fix
  package-lock.json
  package.json
Labels: Passed QA Review

#67 (#65) Analytics: Remove querystring from page name for PageLoad event
  cypress/integration/AppAnalytics/BasicSearchResultsPageLoad.feature
  cypress/integration/AppAnalytics/NoResultsFoundPageLoad.feature
  src/views/Home/Home.jsx
Labels: Needs Technical Review, Passed QA Review

#70 (#53) Pager Visibility for less than results
  cypress/integration/ResultsPagerEnglish.feature
  cypress/integration/common/index.js
  src/components/molecules/search-results-list/search-results-list.jsx
  support/mock-data/Search/cgov/en/all/carcinoma_0-20.json
  support/mock-data/Search/cgov/en/all/mynci_0-20.json
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#69 (#54) Changed Media Type to not be hyperlinked
  cypress/integration/common/index.js
  src/components/molecules/search-results-list/results-list-item.jsx
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#68 (#58) Fixed the logic for findIndexOfLink
  src/components/molecules/best-bet/best-bet.jsx
Labels: Ready to Merge

#73 (#72) No Results Page fix
  src/components/molecules/no-results/no-results.jsx
  src/views/Home/__tests__/Home.en.test.js
Labels: Passed UX Review, Ready to Merge

#86 (#85) dictionary box background color update
  src/components/molecules/definition/definition.scss
Labels: Passed UX Review, Ready to Merge

#84 (#81) Horizontal Scrollbar on Results
  src/components/molecules/search-results-list/search-results-list.scss
Labels: Passed UX Review, Ready to Merge

#82 (#76) Term and phonetic spacing
  src/components/molecules/pronunciation/pronunciation.jsx
  src/components/molecules/pronunciation/pronunciation.scss
  src/views/Home/Home.scss
Labels: Passed UX Review, Ready to Merge

#79 (#78) Adding Margin to Pager Container
  src/components/molecules/search-results-pager/search-results-pager.scss
Labels: Passed UX Review, Ready to Merge

#90 (#88) increase contrast for best bets link
  src/components/molecules/best-bet/best-bet.scss
Labels: Passed UX Review, Ready to Merge

#91 (#89) make pager consistent
  src/components/molecules/search-results-pager/search-results-pager.jsx
Labels: Passed QA Review, Passed UX Review, Ready to Merge

#97 (#94) Bestbets bluebox width
  src/components/molecules/best-bet/best-bet.scss
Labels: Passed UX Review, Ready to Merge

#93 (#92)added integration test for last page of a pager
  cypress/integration/ResultsPagerEnglish.feature
  cypress/integration/ResultsPagerSpanish.feature
  cypress/integration/common/index.js
  support/mock-data/Search/cgov/en/all/tumor_11500-20.json
  support/mock-data/Search/cgov/en/all/tumor_11520-20.json
  support/mock-data/Search/cgov/en/all/tumor_11540-20.json
  support/mock-data/Search/cgov/en/all/tumor_11560-20.json
  support/mock-data/Search/cgov/en/all/tumor_11580-20.json
Labels: Ready to Merge
